version: "3"

services:
  openldap:
    container_name: openldap
    image: pgarrett/ldap-alpine
    restart: always
    ports:
      - "$LDAP_PORT:389"
      - "$LDAPS_PORT:689"
    volumes:
      - "${PWD}/data/ldif:/ldif"
      - "${PWD}/data/certs:/etc/ssl/certs"
      - "${PWD}/data/openldap:/var/lib/openldap/openldap-data"
    environment:
      - TLS_VERIFY_CLIENT=$TLS_VERIFY_CLIENT
      - ORGANISATION_NAME=$ORGANISATION_NAME
      - SUFFIX=$SUFFIX
      - ROOT_USER=$ROOT_USER
      - ROOT_PW=$ROOT_PW
      - USER_UID=$USER_UID
      - USER_GIVEN_NAME=$USER_GIVEN_NAME
      - USER_SURNAME=$USER_SURNAME
      - USER_EMAIL=$USER_EMAIL
      - USER_PW=$USER_PW
      # - ACCESS_CONTROL="access to * by * read"
      - LOG_LEVEL=stats
#     networks:
#       - default

  phpldapadmin:
    image: ghcr.io/sudo-bot/docker-phpldapadmin/docker-phpldapadmin:latest
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'openldap': [{'server': [{'tls': False}]},{'login': [{'bind_id': 'cn=admin,dc=local,dc=host'}]}]}]"
    container_name: phpldapadmin
    hostname: phpldapadmin
    depends_on:
      - openldap
    ports:
      - $LDAPADM_PORT:80
    healthcheck:
      test: ["CMD", "curl", "-s", "--fail", "http://127.0.0.1/.nginx/status"]
      start_period: 5s
      interval: 15s
      timeout: 1s
#     networks:
#       - default

# networks:
#   default:
#     external:
#       name: $NETWORK_NAME
